apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: bakdata
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: microk8s-hostpath
  hostPath:
    path: data/postgres  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: bakdata
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 500Mi
