externalAccess:
  enabled: true
  service:
    broker:
      type: LoadBalancer
      ports:
        external: 9094
    controller:
      type: LoadBalancer
  autoDiscovery:
    enabled: true

broker:
  automountServiceAccountToken: true

controller:
  automountServiceAccountToken: true

persistence:
  size: 2Gi

serviceAccount:
  create: true

rbac:
  create: true
