externalAccess:
  enabled: true
  broker:
    service:
      type: LoadBalancer
      ports:
        external: 9094
    containerPorts:
      external: 9094
  controller:
    service:
      type: LoadBalancer
  autoDiscovery:
    enabled: true

persistence:
  size: 2Gi

serviceAccount:
  create: true

rbac:
  create: true
