apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    listeners:
      listeners:
      - name: external
        port: 9094
        type: nodeport
        tls: false
