apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: postgres-source-connector
  namespace: confluent
spec:
  class: "io.confluent.connect.jdbc.JdbcSourceConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    connection.url: "jdbc:postgresql://192.168.4.21:5432/kafka"
    connection.user: "kafka"
    connection.password: "kafka"
    topic.prefix: "postgres-"
    mode: "incrementing"
    incrementing.column.name: "id"
