apiVersion: v1
kind: Secret
metadata:
  name: debezium-secret
  namespace: kafka
type: Opaque
data:
  username: ZGViZXppdW0= # base64 encoded username: debezium
  password: ZGJ6 # base64 encoded password: dbz