apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: udemy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: codinggandalf/k8s-udemy:networking-frontend-01
        imagePullPolicy: Always
        env:
        - name: AUTH_HOST
          valueFrom:
            configMapKeyRef:
              name: user-config-map
              key: AUTH_HOST
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: udemy
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
