apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasks
  namespace: udemy
spec:
  storageClassName: microk8s-hostpath
  hostPath:
    path: /data/tasks
    type: DirectoryOrCreate
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-pvc
  namespace: udemy
spec:
  storageClassName: microk8s-hostpath
  volumeName: tasks
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
